development: 
  domain: mail.rhomobile.com
  sender: admin@rhomobile.com
  name: Admin
  bbserver: aerobes.aeroprise.com
  iphoneserver: gateway.sandbox.push.apple.com
  iphoneport: 2195
  iphonepassphrase: something
  iphonecert: config/apple_push_cert.pem
    
test:
  domain: mail.rhomobile.com
  sender: admin@rhomobile.com
  name: Admin
  bbserver: aerobes.aeroprise.com
  iphoneserver: gateway.sandbox.push.apple.com
  iphoneport: 2195
  iphonepassphrase: something
  iphonecert: config/apple_push_cert.pem
  
production:
  domain: mail.rhomobile.com
  sender: admin@rhomobile.com
  name: Admin
  bbserver: aerobes.aeroprise.com
  iphoneserver: gateway.push.apple.com
  iphoneport: 2195  
  iphonepassphrase: something
  iphonecert: config/apple_push_cert.pem